### ISSUE TITLE
Web application not operating

### ISSUE THREAD

**Issue by MarPetWue** [CSBiology/deepStabP#11]
Hello,
i got a reply that the web application is again running but this does not seem to be the case. It was able to launch it end of last week but today I just get a message that  https://csb-deepstabp.bio.rptu.de/ is not available. Could it be a problem of my local computer/network? But it is then strange that i could run the application without problems last week.
Would be great if you could give me some feedback.
Thanks and best regards!

**Comment by MarPetWue** [comment]
It seems that the problem has to do with our local network. Sorry.

**Comment by muehlhaus** [comment]
Thank you for the clarification.
