### ISSUE TITLE
Change output table headers

### ISSUE THREAD

**Issue by fejung** [CSBiology/deepStabP#6]
The current output table has "mt" as header. Either change it towards "melting temperature" or towards "Tm". The current "mt" makes it look like it was a typo and not a abbreviation for melting temperature. Also add a metric to the same header to show that we use degree Celsius.
I would suggest one of these two to fix both problems:
Tm [°C]
Melting temperature [°C]

**Comment by Freymaurer** [comment]
`Melting temperature [°C]` done ✨
