### ISSUE TITLE
"Large" fasta files

### ISSUE THREAD

**Issue by fejung** [CSBiology/deepStabP#7]
The website can not handle fasta files that are larger than~ 20Kb. The website returns task was cancelled if I try to use a bigger fasta file. The timeout either needs to be increased or we need to find a different solution to the problem to avoid this.
This is a real problem as we say in the paper that it is possible to do whole proteome analysis with deepSTABp which would mean it must be possible to run the tool with fasta files with sizes of 80'000 to 100'000 Kb.

**Comment by Freymaurer** [comment]
I created a first implementation to handle larger files.
This includes:
- **No limit on upoadable file size** 
Maybe we should set a limit here, as we only support up to 1000 fasta items anyways, and ~80mb fasta files are around 200k items. @ZimmerD @fejung 
- **Incremental result feedback**
All given fasta items are binned per 10 items and processed incrementally. All data is stored on the server and only results are sent back in small packages. 
The use will see something like (0/4) -> (1/4) ... and so on.
![image](https://user-images.githubusercontent.com/39732517/230128245-972b8f74-9d10-435f-9ef2-bdc6a1b84d63.png)


Next step will be to update python api according to the changes. As we now do the fasta parsing on the dotnet side, this should reduce workload on the python side.

**Comment by Freymaurer** [comment]
Done! 🎉
