### ISSUE TITLE
Web application not working

### ISSUE THREAD

**Issue by MarPetWue** [CSBiology/deepStabP#9]
I tried to use https://csb-deepstabp.bio.rptu.de/ with google chrome (04/10/2023) but got the following error message:
Die Website ist nicht erreichbar
Prüfe, ob „csb-deepstabp.bio.rptu.de“ einen Tippfehler enthält.
Wenn die URL keinen Tippfehler enthält, [kannst du die Windows-Netzwerkdiagnose durchführen](javascript:diagnoseErrors()).
DNS_PROBE_FINISHED_NXDOMAIN
Is the page currently not maintained?

**Comment by ZimmerD** [comment]
closed, see #10
